// AUTO-GENERATED by scripts/morphometry.mjs --write. Fitted proportion
// leaves that converge each species onto the sourced ground-truth ratios
// (REFERENCES in that script). Do not hand-edit; re-run the fit instead.
export default {
  "jewel_beetle": {
    "body": {
      "head": {
        "len": 0.108,
        "h": 0.157
      },
      "thorax": {
        "len": 0.238,
        "h": 0.208
      },
      "abdomen": {
        "len": 0.704,
        "h": 0.26
      }
    },
    "legs": {
      "femur": 0.077,
      "tibia": 0.086,
      "tarsus": 0.047
    },
    "head": {
      "eye": 0.063
    },
    "antennae": {
      "len": 0.195
    }
  },
  "ladybird": {
    "body": {
      "head": {
        "len": 0.029,
        "h": 0.064
      },
      "thorax": {
        "len": 0.058,
        "h": 0.091
      },
      "abdomen": {
        "len": 0.177,
        "h": 0.164
      }
    },
    "legs": {
      "femur": 0.002,
      "tibia": 0.002,
      "tarsus": 0.001
    },
    "head": {
      "eye": 0.014
    },
    "antennae": {
      "len": 0.042
    }
  },
  "mantis": {
    "body": {
      "head": {
        "len": 0.791,
        "h": 1.034
      },
      "thorax": {
        "len": 4.068,
        "h": 1.25
      },
      "abdomen": {
        "len": 6.78,
        "h": 1.469
      }
    },
    "legs": {
      "femur": 4.279,
      "tibia": 4.105,
      "tarsus": 2.566
    },
    "head": {
      "eye": 0.393
    },
    "antennae": {
      "len": 2.486
    },
    "wings": {
      "len": 10.621
    }
  },
  "dragonfly": {
    "body": {
      "head": {
        "len": 0.121,
        "h": 0.142
      },
      "thorax": {
        "len": 0.242,
        "h": 0.177
      },
      "abdomen": {
        "len": 0.94,
        "h": 0.085
      }
    },
    "legs": {
      "femur": 0.055,
      "tibia": 0.063,
      "tarsus": 0.037
    },
    "head": {
      "eye": 0.106
    },
    "antennae": {
      "len": 0.027
    },
    "wings": {
      "len": 0.86
    }
  },
  "honeybee": {
    "body": {
      "head": {
        "len": 0.285,
        "h": 0.228
      },
      "thorax": {
        "len": 0.268,
        "h": 0.337
      },
      "abdomen": {
        "len": 0.611,
        "h": 0.337
      }
    },
    "legs": {
      "femur": 0.231,
      "tibia": 0.262,
      "tarsus": 0.155
    },
    "head": {
      "eye": 0.267
    },
    "antennae": {
      "len": 0.372
    },
    "wings": {
      "len": 0.791
    }
  },
  "housefly": {
    "body": {
      "head": {
        "len": 0.036,
        "h": 0.069
      },
      "thorax": {
        "len": 0.064,
        "h": 0.075
      },
      "abdomen": {
        "len": 0.102,
        "h": 0.075
      }
    },
    "legs": {
      "femur": 0.016,
      "tibia": 0.018,
      "tarsus": 0.011
    },
    "head": {
      "eye": 0.035
    },
    "antennae": {
      "len": 0.015
    },
    "wings": {
      "len": 0.213
    }
  },
  "mosquito": {
    "body": {
      "head": {
        "len": 0.009,
        "h": 0.009
      },
      "thorax": {
        "len": 0.024,
        "h": 0.015
      },
      "abdomen": {
        "len": 0.052,
        "h": 0.007
      }
    },
    "legs": {
      "femur": 0.024,
      "tibia": 0.029,
      "tarsus": 0.019
    },
    "head": {
      "eye": 0.014
    },
    "antennae": {
      "len": 0.038
    },
    "wings": {
      "len": 0.059
    }
  }
};
