// AUTO-GENERATED by scripts/morphometry.mjs --write. Fitted proportion
// leaves that converge each species onto the sourced ground-truth ratios
// (REFERENCES in that script). Do not hand-edit; re-run the fit instead.
export default {
  "jewel_beetle": {
    "body": {
      "head": {
        "len": 0.09,
        "h": 0.131
      },
      "thorax": {
        "len": 0.198,
        "h": 0.173
      },
      "abdomen": {
        "len": 0.586,
        "h": 0.216
      }
    },
    "legs": {
      "femur": 0.057,
      "tibia": 0.064,
      "tarsus": 0.035
    },
    "head": {
      "eye": 0.052
    },
    "antennae": {
      "len": 0.162
    }
  },
  "ladybird": {
    "body": {
      "head": {
        "len": 0.029,
        "h": 0.064
      },
      "thorax": {
        "len": 0.058,
        "h": 0.091
      },
      "abdomen": {
        "len": 0.177,
        "h": 0.164
      }
    },
    "legs": {
      "femur": 0.001,
      "tibia": 0.001,
      "tarsus": 0.001
    },
    "head": {
      "eye": 0.014
    },
    "antennae": {
      "len": 0.042
    }
  },
  "mantis": {
    "body": {
      "head": {
        "len": 0.944,
        "h": 1.235
      },
      "thorax": {
        "len": 4.857,
        "h": 1.493
      },
      "abdomen": {
        "len": 8.096,
        "h": 1.754
      }
    },
    "legs": {
      "femur": 5.119,
      "tibia": 4.911,
      "tarsus": 3.07
    },
    "head": {
      "eye": 0.469
    },
    "antennae": {
      "len": 2.968
    },
    "wings": {
      "len": 12.683
    }
  },
  "dragonfly": {
    "body": {
      "head": {
        "len": 0.101,
        "h": 0.119
      },
      "thorax": {
        "len": 0.201,
        "h": 0.148
      },
      "abdomen": {
        "len": 0.783,
        "h": 0.071
      }
    },
    "legs": {
      "femur": 0.039,
      "tibia": 0.045,
      "tarsus": 0.026
    },
    "head": {
      "eye": 0.088
    },
    "antennae": {
      "len": 0.022
    },
    "wings": {
      "len": 0.716
    }
  },
  "honeybee": {
    "body": {
      "head": {
        "len": 0.285,
        "h": 0.228
      },
      "thorax": {
        "len": 0.268,
        "h": 0.338
      },
      "abdomen": {
        "len": 0.611,
        "h": 0.338
      }
    },
    "legs": {
      "femur": 0.231,
      "tibia": 0.262,
      "tarsus": 0.155
    },
    "head": {
      "eye": 0.178
    },
    "antennae": {
      "len": 0.372
    },
    "wings": {
      "len": 0.792
    }
  },
  "housefly": {
    "body": {
      "head": {
        "len": 0.027,
        "h": 0.051
      },
      "thorax": {
        "len": 0.047,
        "h": 0.055
      },
      "abdomen": {
        "len": 0.075,
        "h": 0.055
      }
    },
    "legs": {
      "femur": 0.005,
      "tibia": 0.006,
      "tarsus": 0.003
    },
    "head": {
      "eye": 0.025
    },
    "antennae": {
      "len": 0.011
    },
    "wings": {
      "len": 0.156
    }
  },
  "mosquito": {
    "body": {
      "head": {
        "len": 0.005,
        "h": 0.005
      },
      "thorax": {
        "len": 0.013,
        "h": 0.008
      },
      "abdomen": {
        "len": 0.028,
        "h": 0.004
      }
    },
    "legs": {
      "femur": 0.004,
      "tibia": 0.004,
      "tarsus": 0.003
    },
    "head": {
      "eye": 0.007
    },
    "antennae": {
      "len": 0.02
    },
    "wings": {
      "len": 0.031
    }
  }
};
