// AUTO-GENERATED by scripts/morphometry.mjs --write. Fitted proportion
// leaves that converge each species onto the sourced ground-truth ratios
// (REFERENCES in that script). Do not hand-edit; re-run the fit instead.
export default {
  "jewel_beetle": {
    "body": {
      "head": {
        "len": 0.075,
        "h": 0.109
      },
      "thorax": {
        "len": 0.165,
        "h": 0.144
      },
      "abdomen": {
        "len": 0.488,
        "h": 0.18
      }
    },
    "legs": {
      "femur": 0.041,
      "tibia": 0.046,
      "tarsus": 0.025
    },
    "head": {
      "eye": 0.044
    },
    "antennae": {
      "len": 0.135
    }
  },
  "ladybird": {
    "body": {
      "head": {
        "len": 0.029,
        "h": 0.064
      },
      "thorax": {
        "len": 0.058,
        "h": 0.091
      },
      "abdomen": {
        "len": 0.177,
        "h": 0.164
      }
    },
    "legs": {
      "femur": 0.001,
      "tibia": 0.001,
      "tarsus": 0.001
    },
    "head": {
      "eye": 0.014
    },
    "antennae": {
      "len": 0.042
    }
  },
  "mantis": {
    "body": {
      "head": {
        "len": 1.128,
        "h": 1.475
      },
      "thorax": {
        "len": 5.8,
        "h": 1.783
      },
      "abdomen": {
        "len": 9.666,
        "h": 2.094
      }
    },
    "legs": {
      "femur": 6.121,
      "tibia": 5.872,
      "tarsus": 3.671
    },
    "head": {
      "eye": 0.56
    },
    "antennae": {
      "len": 3.544
    },
    "wings": {
      "len": 15.144
    }
  },
  "dragonfly": {
    "body": {
      "head": {
        "len": 0.084,
        "h": 0.099
      },
      "thorax": {
        "len": 0.168,
        "h": 0.123
      },
      "abdomen": {
        "len": 0.652,
        "h": 0.059
      }
    },
    "legs": {
      "femur": 0.026,
      "tibia": 0.03,
      "tarsus": 0.018
    },
    "head": {
      "eye": 0.073
    },
    "antennae": {
      "len": 0.019
    },
    "wings": {
      "len": 0.596
    }
  },
  "honeybee": {
    "body": {
      "head": {
        "len": 0.303,
        "h": 0.243
      },
      "thorax": {
        "len": 0.256,
        "h": 0.361
      },
      "abdomen": {
        "len": 0.605,
        "h": 0.361
      }
    },
    "legs": {
      "femur": 0.231,
      "tibia": 0.262,
      "tarsus": 0.155
    },
    "head": {
      "eye": 0.158
    },
    "antennae": {
      "len": 0.372
    },
    "wings": {
      "len": 0.791
    }
  },
  "housefly": {
    "body": {
      "head": {
        "len": 0.02,
        "h": 0.038
      },
      "thorax": {
        "len": 0.035,
        "h": 0.041
      },
      "abdomen": {
        "len": 0.055,
        "h": 0.041
      }
    },
    "legs": {
      "femur": 0.001,
      "tibia": 0.001,
      "tarsus": 0
    },
    "head": {
      "eye": 0.019
    },
    "antennae": {
      "len": 0.008
    },
    "wings": {
      "len": 0.115
    }
  },
  "mosquito": {
    "body": {
      "head": {
        "len": 0.003,
        "h": 0.003
      },
      "thorax": {
        "len": 0.007,
        "h": 0.004
      },
      "abdomen": {
        "len": 0.015,
        "h": 0.002
      }
    },
    "legs": {
      "femur": 0,
      "tibia": 0,
      "tarsus": 0
    },
    "head": {
      "eye": 0.004
    },
    "antennae": {
      "len": 0.011
    },
    "wings": {
      "len": 0.017
    }
  }
};
